var myProjects = [{
    title: 'google',
    category: 'search-engine',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum iaculis justo ante, at maximus mauris ornare eu. Morbi aliquet aliquam ipsum. Integer sodales sapien vel pellentesque posuere. Vestibulum id placerat lacus, vel feugiat nisl. Etiam facilisis massa non sapien convallis imperdiet. Nulla facilisi. Duis tincidunt, dolor et mollis ultrices, purus nulla suscipit mi, rhoncus facilisis lectus turpis vel mi. Donec dictum elementum vulputate. Nulla porta vulputate luctus. Aliquam pharetra diam sit amet pellentesque ultrices. Donec at est aliquet, fermentum quam et, ullamcorper quam. Sed metus orci, facilisis ac fringilla quis, placerat a sem. Sed eget molestie est, eleifend dignissim sem. Morbi egestas nibh a lectus feugiat ullamcorper. Morbi elementum tristique augue sit amet rutrum.Aenean commodo sed purus et bibendum. Morbi a ullamcorper lorem. Curabitur nec ex mauris. Nulla suscipit, urna vel placerat consequat, lectus tortor luctus enim, venenatis porta erat justo eu mauris. Quisque euismod sem at nulla porta, a dictum augue mollis. Nulla dictum, neque eget vestibulum interdum, lorem mi faucibus turpis, vitae interdum ante turpis ut ipsum. Vestibulum quis libero malesuada lectus venenatis pellentesque. Sed eleifend dapibus magna, id varius nibh venenatis at. Phasellus finibus neque elit, id bibendum augue aliquam a. Nunc vehicula id tortor nec pharetra. Vestibulum neque diam, finibus in ante sit amet, hendrerit consectetur ex. Donec commodo augue sed leo suscipit, nec imperdiet nunc consequat. Etiam ullamcorper sagittis diam a placerat. Nullam lobortis dictum erat ut tempor.'
}, {
    title: 'google',
    category: 'search-engine',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum iaculis justo ante, at maximus mauris ornare eu. Morbi aliquet aliquam ipsum. Integer sodales sapien vel pellentesque posuere. Vestibulum id placerat lacus, vel feugiat nisl. Etiam facilisis massa non sapien convallis imperdiet. Nulla facilisi. Duis tincidunt, dolor et mollis ultrices, purus nulla suscipit mi, rhoncus facilisis lectus turpis vel mi. Donec dictum elementum vulputate. Nulla porta vulputate luctus. Aliquam pharetra diam sit amet pellentesque ultrices. Donec at est aliquet, fermentum quam et, ullamcorper quam. Sed metus orci, facilisis ac fringilla quis, placerat a sem. Sed eget molestie est, eleifend dignissim sem. Morbi egestas nibh a lectus feugiat ullamcorper. Morbi elementum tristique augue sit amet rutrum.Aenean commodo sed purus et bibendum. Morbi a ullamcorper lorem. Curabitur nec ex mauris. Nulla suscipit, urna vel placerat consequat, lectus tortor luctus enim, venenatis porta erat justo eu mauris. Quisque euismod sem at nulla porta, a dictum augue mollis. Nulla dictum, neque eget vestibulum interdum, lorem mi faucibus turpis, vitae interdum ante turpis ut ipsum. Vestibulum quis libero malesuada lectus venenatis pellentesque. Sed eleifend dapibus magna, id varius nibh venenatis at. Phasellus finibus neque elit, id bibendum augue aliquam a. Nunc vehicula id tortor nec pharetra. Vestibulum neque diam, finibus in ante sit amet, hendrerit consectetur ex. Donec commodo augue sed leo suscipit, nec imperdiet nunc consequat. Etiam ullamcorper sagittis diam a placerat. Nullam lobortis dictum erat ut tempor.'
}, {
    title: 'google',
    category: 'search-engine',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum iaculis justo ante, at maximus mauris ornare eu. Morbi aliquet aliquam ipsum. Integer sodales sapien vel pellentesque posuere. Vestibulum id placerat lacus, vel feugiat nisl. Etiam facilisis massa non sapien convallis imperdiet. Nulla facilisi. Duis tincidunt, dolor et mollis ultrices, purus nulla suscipit mi, rhoncus facilisis lectus turpis vel mi. Donec dictum elementum vulputate. Nulla porta vulputate luctus. Aliquam pharetra diam sit amet pellentesque ultrices. Donec at est aliquet, fermentum quam et, ullamcorper quam. Sed metus orci, facilisis ac fringilla quis, placerat a sem. Sed eget molestie est, eleifend dignissim sem. Morbi egestas nibh a lectus feugiat ullamcorper. Morbi elementum tristique augue sit amet rutrum.Aenean commodo sed purus et bibendum. Morbi a ullamcorper lorem. Curabitur nec ex mauris. Nulla suscipit, urna vel placerat consequat, lectus tortor luctus enim, venenatis porta erat justo eu mauris. Quisque euismod sem at nulla porta, a dictum augue mollis. Nulla dictum, neque eget vestibulum interdum, lorem mi faucibus turpis, vitae interdum ante turpis ut ipsum. Vestibulum quis libero malesuada lectus venenatis pellentesque. Sed eleifend dapibus magna, id varius nibh venenatis at. Phasellus finibus neque elit, id bibendum augue aliquam a. Nunc vehicula id tortor nec pharetra. Vestibulum neque diam, finibus in ante sit amet, hendrerit consectetur ex. Donec commodo augue sed leo suscipit, nec imperdiet nunc consequat. Etiam ullamcorper sagittis diam a placerat. Nullam lobortis dictum erat ut tempor.'
}]
